apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "legate.fullname" . }}-config
  labels:
    {{- include "legate.labels" . | nindent 4 }}
data:
  legate.yml: |
    {{- .Values.legateConfig | nindent 4 }}
